List and export added hosts.

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -36,8 +36,9 @@ usage() {
 	echo "  $(bold config)          Print configuration options."
 	echo "  $(bold name)            Print this systems name."
 	echo "  $(bold top)             List connections and statistics."
-	echo "  $(bold export)          Export this systems keys"
+	echo "  $(bold export) $(dim "[name]")   Export this systems keys"
 	echo "  $(bold add)             Add another systems exported keys."
+	echo "  $(bold list)            List added hosts."
 	echo "  $(bold restart)         Restart tincd service."
 	echo
 	echo " Advanced:"
@@ -93,6 +94,19 @@ about() {
 
 help_add() {
 	echo "This is an import followed by and automatic \"snap set tunnel connect\""
+
+	exit 0
+}
+
+help_list() {
+	echo "List added hosts, type $(bold tunnel dump) $(dim name) to display the file."
+
+	exit 0
+}
+
+help_export() {
+	echo "Export host configuration of local node to standard output, or export"
+	echo "the specified hosts configuration file."
 
 	exit 0
 }
@@ -154,7 +168,28 @@ case "$1" in
 		snapctl set connect=$c
 		rm $SNAP_DATA/tmp/import-data
 		;;
-	top|import|export|export-all|exchange|exchange-all)
+	list)
+		[ "x$SHOW_HELP_SECTION" == xyes ] && help_list
+
+		ls -1 $SNAP_DATA/tinc/hosts/
+		;;
+	export)
+		if [ $UID != 0 ]; then
+			echo "You need to run this as root, try $(bold sudo tunnel $@)"
+			exit 1
+		fi
+
+		[ "x$SHOW_HELP_SECTION" == xyes ] && help_export
+
+		if [ -z $2 ]; then
+			tinc -c $SNAP_DATA/tinc/ --pidfile=$SNAP_DATA/tinc/pid export
+		elif [ -f "$SNAP_DATA/tinc/hosts/$2" ]; then
+			cat "$SNAP_DATA/tinc/hosts/$2"
+		else
+			echo "host $2 not found"
+		fi
+		;;
+	top|import|export-all|exchange|exchange-all)
 		if [ $UID != 0 ]; then
 			echo "You need to run this as root, try $(bold sudo tunnel $@)"
 			exit 1
